#--- Site settings ---#

title: IREE
email: iree-discuss@googlegroups.com
description: >-
  IREE documentation hub
# The base hostname & protocol for the site
url: "https://google.github.io"
# The subpath of the site
baseurl: "/iree/"

permalink: pretty

#--- Theme settings ---#

remote_theme: pmarsceill/just-the-docs@v0.2.9
# Enable or disable the site search
search_enabled: true

# Auxiliary links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/google/IREE"
  "Discord":
    - "https://discord.gg/26P4xW4"

#--- Jekyll settings ---#

# Exclude the following files from being processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
